name: HTML Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Validate HTML
        run: htmlhint index.html
